#!/bin/bash

zathura /home/ashep/Share/Documents/Study/Strohmayer\ S.,\ Jordan\ T.\ -\ CompTIA\ Linux+\ Certification\ All-in-One\ Exam\ Guide,\ 2nd\ Edition\ \(Exam\ XK0-005\)\ -\ 2023/'Strohmayer S., Jordan T. - CompTIA Linux+ Certification All-in-One Exam Guide, 2nd Edition (Exam XK0-005) - 2023.pdf'
