#!/bin/bash

temp=$("$HOME/bin/temp" | grep CPU | cut -d'-' -f2 | sed 's/ //' | cut -d'.' -f1)

echo "$temp"
echo "$temp" >> /tmp/cputemp.txt

if [ "$temp" -gt 80 ]; then
	/usr/bin/notify-send "CPU TEMP WARNING" "CPU temp is too high! "
fi

tail -n 360 /tmp/cputemp.txt > /tmp/cputemp.txt.tmp && mv /tmp/cputemp.txt.tmp /tmp/cputemp.txt

