#!/bin/bash

KEY_PATH="/home/ashep/.ssh/ansible"

# Check if SSH agent is running
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    eval "$(ssh-agent)"
    ssh-add "$KEY_PATH"
else
    # Check if the key is already added
    if ! ssh-add -l | grep -q "$(ssh-keygen -lf $KEY_PATH | awk '{print $2}')"; then
        ssh-add "$KEY_PATH"
    fi
fi

# SSH into the server
ssh trixie2@192.168.1.199
